<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseDescriptionSeeder extends Seeder
{
    public function run(): void
    {
        $descriptions = [
            'barbell_bench_press' => "Sdraiato sulla panca, impugnatura leggermente più larga delle spalle. Abbassa il bilanciere al petto toccando la zona sternale inferiore, poi spingi verso l'alto in traiettoria leggermente obliqua verso il rack. Scapole retratte e depresse per tutto il movimento.",
            'dumbbell_bench_press' => "Sdraiato sulla panca, manubri ai lati del petto con i gomiti a circa 75°. Abbassa controllando la discesa fino a sentire stiramento pettorale, poi spingi verso l'alto e leggermente verso il centro senza bloccare i gomiti in cima.",
            'incline_barbell_bench_press' => "Panca inclinata a 30-45°. Impugnatura come per la piana. Abbassa il bilanciere verso la parte alta del petto/clavicola, spingi verso l'alto e leggermente dietro la testa. Il deltoide anteriore lavora più della versione piana.",
            'incline_dumbbell_bench_press' => "Panca inclinata a 30-45°. Partenza con manubri in alto, abbassa aprendo i gomiti fino a sentire stiramento nella parte alta del petto, poi spingi verso l'alto convergendo leggermente le mani.",
            'decline_barbell_bench_press' => 'Panca declinata (piedi in alto). Abbassa il bilanciere verso la parte bassa del petto/addome superiore. Traiettoria più verticale rispetto alla piana. Isola maggiormente il pettorale sternale inferiore.',
            'cable_chest_fly' => 'In piedi tra i due cavi alti. Braccia leggermente flesse con gomiti fissi. Porta le mani verso il basso e al centro in un arco ampio, contraendo il pettorale in chiusura. Ritorna lentamente al punto di partenza controllando lo stiramento.',
            'pec_deck_machine' => "Seduto alla macchina, gomiti appoggiati ai cuscinetti all'altezza delle spalle. Chiudi le braccia verso il centro senza strappare, contraendo il petto al massimo. Ritorna lentamente senza perdere tensione.",
            'chest_dips' => "Alle parallele, busto inclinato in avanti di circa 30°. Abbassa il corpo fino a sentire stiramento nel petto (gomiti verso l'esterno), poi spingi verso l'alto mantenendo l'inclinazione. La verticalità del busto sposta il lavoro sui tricipiti.",
            'machine_chest_press' => 'Seduto alla macchina con schiena appoggiata allo schienale. Spingi le maniglie in avanti in modo controllato, estendi quasi completamente le braccia, poi ritorna lentamente senza far tornare il peso a battuta.',
            'smith_incline_press' => 'Panca inclinata posizionata sotto lo Smith Machine. Sblocca il bilanciere e abbassalo verso la parte alta del petto. Lo Smith elimina la componente di equilibrio ma fissa la traiettoria: assicurati che corrisponda alla tua biomeccanica.',
            'push_up' => "Mani a terra leggermente più larghe delle spalle, corpo in linea retta dai talloni alla testa. Abbassa il petto verso il suolo mantenendo il core contratto, poi spingi verso l'alto. La larghezza dell'impugnatura determina l'enfasi su petto o tricipiti.",
            'conventional_deadlift' => 'Piedi alla larghezza dei fianchi, bilanciere sui piedi. Prendi la presa con mani fuori le gambe. Schiena neutra, petto alto. Spingi il pavimento via dai piedi mantenendo il bilanciere aderente alle gambe durante tutta la salita. In cima, anca e ginocchio completamente estesi.',
            'romanian_deadlift' => "Partenza in piedi con bilanciere in mano. Cerniera sull'anca mantenendo la schiena neutra: abbassa il bilanciere lungo le gambe fino a sentire forte stiramento negli ischiocrurali (tipicamente sotto il ginocchio), poi torna su spingendo l'anca in avanti.",
            'pull_up_pronated' => 'Presa prona larga, braccia tese come punto di partenza. Tira il petto verso la sbarra portando i gomiti verso il basso e indietro. Contrai il dorsale in cima, poi scendi lentamente fino a distensione completa.',
            'chin_up_supinated' => "Presa supina alla larghezza delle spalle. Tira verso l'alto portando il mento sopra la sbarra. La presa supina coinvolge maggiormente il bicipite rispetto alla presa prona. Scendi lentamente a braccia quasi tese.",
            'lat_pulldown_front' => 'Seduto alla lat machine, presa larga prona. Tira la barra verso il petto superiore portando i gomiti verso il basso e dietro. Non oscillare col busto. Contrai il dorsale in basso, poi risali lentamente controllando.',
            'seated_cable_row' => "Seduto con piedi sui poggiapiedi, schiena neutra. Tira la maniglia verso l'addome portando i gomiti indietro e le scapole a stringersi. Petto fuori per tutto il movimento. Ritorna lentamente con distensione controllata delle braccia.",
            'barbell_row' => "Busto inclinato a circa 45° con schiena neutra, bilanciere in presa prona. Tira verso l'ombelico portando i gomiti dietro il tronco. Non usare il rimbalzo della schiena per sollevare. Scapole che si stringono al top del movimento.",
            'one_arm_dumbbell_row' => "Un ginocchio e una mano appoggiate sulla panca. Tira il manubrio verso l'anca (non verso la spalla) portando il gomito indietro e alto. Mantieni il tronco parallelo al suolo. Un set per lato.",
            't_bar_row' => 'Busto inclinato, impugnatura sulla barra T o triangolo al cavo. Tira verso il petto portando i gomiti indietro. Il range di movimento spesso è minore del rematore con bilanciere ma permette carichi elevati con buona tenuta lombare.',
            'cable_pullover' => 'In piedi di fronte al cavo alto, maniglie prese sopra la testa con gomiti leggermente flessi. Porta le mani verso i fianchi in un arco, mantenendo i gomiti fissi. Isola il dorsale in modo eccellente; utile come esercizio di connessione mente-muscolo.',
            'chest_supported_row' => "Busto appoggiato su una panca inclinata, manubri che pendono. Tira i manubri verso i fianchi portando i gomiti indietro. L'appoggio al petto elimina la compensazione lombare e isola meglio la schiena alta.",
            'machine_row' => 'Seduto alla macchina con petto sul supporto. Tira le maniglie verso di te portando i gomiti indietro. Macchina guidata: ideale per principianti o come finisher ad alta rep con stretto controllo.',
            'straight_arm_pulldown' => 'In piedi di fronte al cavo alto, barra presa con braccia quasi tese. Mantieni i gomiti fissi e porta la barra verso le cosce descrivendo un arco ampio. Isola il dorsale quasi esclusivamente, ottimo per la connessione mente-muscolo.',
            'rack_pull' => 'Bilanciere su blocchi o rack a metà stinco. Esegui come lo stacco convenzionale ma con range ridotto. Permette carichi superiori allo stacco completo; enfatizza erettori spinali, glutei e upper back nella fase di lock-out.',
            'overhead_press_standing' => 'In piedi, bilanciere a livello del mento presa leggermente più larga delle spalle. Spingi verticalmente sopra la testa estendendo le braccia, poi abbassa controllato al mento. Core contratto per proteggere la lombare. La traiettoria è leggermente dietro la testa in cima.',
            'seated_dumbbell_press' => "Seduto con schiena supportata, manubri all'altezza delle orecchie. Spingi verso l'alto fino a quasi estendere le braccia, poi abbassa lentamente. Rispetto al bilanciere permette un range più libero e meno stress sull'articolazione AC.",
            'arnold_press' => "Partenza con manubri davanti al viso, palme verso di te (come la cima di un curl). Ruota le mani verso l'esterno man mano che sali, fino ad arrivare con palme in avanti in cima. Coinvolge tutto il deltoide grazie alla rotazione.",
            'dumbbell_lateral_raise' => "In piedi o seduto, manubri ai fianchi. Alza le braccia lateralmente con gomiti leggermente flessi fino all'altezza delle spalle (non oltre). Il mignolo può essere leggermente più alto del pollice ('versa il bicchiere'). Abbassa lentamente.",
            'cable_lateral_raise' => "Cavo basso sul lato opposto al braccio di lavoro. Alza il braccio lateralmente fino all'altezza della spalla. Il cavo mantiene tensione costante anche nella fase bassa, a differenza del manubrio. Un lato alla volta.",
            'reverse_pec_deck' => "Seduto alla pec deck al contrario (petto verso il supporto) o con le braccia che aprono invece di chiudersi. Apri le braccia verso l'esterno mantenendo i gomiti leggermente flessi. Contrai il deltoide posteriore e i romboidi in apertura.",
            'bent_over_rear_delt_raise' => 'Busto inclinato in avanti di circa 70-90°, manubri che pendono. Alza le braccia lateralmente verso il soffitto con gomiti leggermente flessi. Evita di ruotare le spalle o usare il trapezio superiore.',
            'upright_row' => "Bilanciere in presa prona stretta davanti alle cosce. Tira verso il mento portando i gomiti in alto e verso l'esterno. Attenzione: presa troppo stretta può causare impingement di spalla. Fermati quando i gomiti raggiungono l'altezza delle spalle.",
            'cable_rear_delt_fly' => "Due cavi alti incrociati. Parti con le mani incrociate al centro e apri le braccia verso l'esterno e leggermente il basso, come per abbracciare un cerchio grande. Isola il deltoide posteriore con tensione costante dal cavo.",
            'machine_lateral_raise' => "Seduto alla macchina, braccia appoggiate sui cuscinetti. Spingi lateralmente verso l'alto fino all'altezza della spalla. La macchina guida il movimento e mantiene tensione anche nella fase bassa del ROM.",
            'barbell_curl' => "In piedi, bilanciere in presa supina alla larghezza delle spalle. Tieni i gomiti fissi ai fianchi e porta il bilanciere verso le spalle flettendo solo l'avambraccio. Abbassa lentamente fino a quasi estensione completa.",
            'alternating_dumbbell_curl' => "In piedi, manubri ai fianchi. Alza un braccio alla volta portando il manubrio verso la spalla con eventuale supinazione del polso. L'alternanza permette di concentrarsi su un braccio per volta. Gomiti fissi.",
            'scott_curl' => "Gomiti appoggiati sul bancale inclinato della panca Scott, bilanciere o EZ-bar in mano. Estendi quasi completamente le braccia nella fase bassa, poi porta il bilanciere verso le spalle. Il supporto impedisce di usare l'inerzia.",
            'hammer_curl' => 'In piedi, manubri ai fianchi con presa neutra (pollice in alto). Porta il manubrio verso la spalla senza ruotare il polso. Questa presa enfatizza il brachiale e il brachioradiale rispetto al bicipite.',
            'cable_curl' => 'In piedi di fronte al cavo basso, barra o maniglie in presa supina. Porta le mani verso le spalle mantenendo i gomiti fermi. Il cavo mantiene tensione nella fase bassa e alta del movimento a differenza del bilanciere.',
            'concentration_curl' => "Seduto, gomito appoggiato all'interno della coscia. Porta il manubrio verso la spalla con movimento lento e controllato. Ottima connessione mente-muscolo. Non ruotare il tronco per aiutare il sollevamento.",
            'incline_dumbbell_curl' => 'Sdraiato su panca inclinata a 45-60°, manubri che pendono liberamente. Il gomito è dietro il tronco nella fase bassa, creando maggiore stiramento del bicipite rispetto al curl standard. Porta i manubri verso le spalle.',
            'bayesian_curl' => 'In piedi di fronte al cavo basso con il cavo che parte da dietro. Il braccio è esteso dietro il tronco nella partenza, massimizzando lo stiramento del bicipite. Porta la mano verso la spalla mantenendo il gomito nella stessa posizione.',
            'ez_bar_french_press' => "Sdraiato sulla panca, bilanciere EZ sopra la testa con braccia quasi tese. Abbassa l'EZ verso la fronte o sopra la testa piegando solo i gomiti (che rimangono fissi). Estendi poi verso l'alto. Il grip EZ riduce lo stress sui polsi.",
            'cable_pushdown_straight' => 'In piedi di fronte al cavo alto, barra diritta in presa prona. Gomiti ai fianchi e fissi. Spingi la barra verso il basso fino a estensione completa delle braccia, poi risali lentamente fino a circa 90°. Non portare i gomiti in avanti.',
            'cable_pushdown_rope' => "Come il push down con sbarra ma con la corda. In cima puoi aprire le mani verso l'esterno per aumentare il range e la contrazione finale del tricipite. La corda permette un movimento più naturale per i polsi.",
            'triceps_dips' => "Alle parallele con busto verticale (non inclinato). Abbassa il corpo piegando i gomiti verso l'esterno fino a circa 90°, poi spingi verso l'alto. La posizione verticale del busto sposta il lavoro principalmente sui tricipiti.",
            'skullcrusher' => "Sdraiato sulla panca, bilanciere o EZ-bar sopra la testa con braccia quasi tese. Abbassa il peso verso la fronte o sopra la testa piegando i gomiti. I gomiti devono rimanere fermi e verticali. Estendi verso l'alto in modo esplosivo.",
            'close_grip_bench_press' => "Panca piana con presa stretta (pollici a circa 30-40 cm di distanza). Abbassa il bilanciere verso il basso del petto/addome superiore, poi spingi verso l'alto. Gomiti più vicini al corpo rispetto alla panca classica per enfatizzare il tricipite.",
            'overhead_cable_extension' => 'Schiena al cavo alto, corda impugnata dietro la testa. Estendi i gomiti verso il basso e in avanti portando la corda davanti a te. La posizione overhead massimizza lo stiramento della testa lunga del tricipite.',
            'single_arm_cable_pushdown' => 'Come il push down standard ma con un solo braccio e maniglia singola. Permette di correggere squilibri tra i lati e di lavorare con una presa più naturale. Un set per braccio.',
            'jm_press' => 'Incrocio tra panca stretta e skullcrusher. Sdraiato sulla panca, abbassa il bilanciere verso il basso del collo/clavicole lasciando che i gomiti si muovano in avanti. Movimento ibrido che enfatizza molto i tricipiti con alto carico.',
            'back_squat_high_bar' => 'Bilanciere appoggiato in posizione alta sui trapezi (non sul collo). Piedi alla larghezza delle spalle, punte leggermente aperte. Scendi mantenendo il petto alto e le ginocchia in linea con le punte fino a parallelismo o sotto. Risali spingendo il pavimento via.',
            'front_squat' => 'Bilanciere in presa frontale (grip olimpico o cross-grip) appoggiato sulle clavicole. Gomiti alti per tenerlo in posizione. Più torso verticale rispetto al back squat, maggiore enfasi sul quadricipite. Richiede ottima mobilità di polso e caviglia.',
            'hack_squat_machine' => "Schiena appoggiata alla macchina inclinata, piedi sulla pedana. Scendi flettendo le ginocchia portandole verso il petto, poi spingi verso l'alto. La pedana può essere posizionata più o meno in alto per cambiare l'enfasi muscolare.",
            'leg_press_45' => 'Seduto nella macchina, piedi sulla pedana alla larghezza delle spalle. Abbassa il peso flettendo le ginocchia verso il petto (non oltre 90°), poi spingi via. Non bloccare mai completamente le ginocchia in cima e non lasciare che il basso schiena si sollevi dalla seduta.',
            'barbell_lunge' => 'Bilanciere sul dorso, fai un passo avanti lungo. Abbassa il ginocchio posteriore quasi a terra mantenendo il busto verticale, poi spingi col piede anteriore per tornare alla posizione di partenza. Alterna le gambe a ogni rep.',
            'bulgarian_split_squat' => "Piede posteriore appoggiato su una panca, piede anteriore avanzato. Abbassa il ginocchio posteriore verso il suolo mantenendo il busto verticale o leggermente inclinato. Poi spingi verso l'alto col piede anteriore. Un set per gamba.",
            'leg_extension' => "Seduto alla macchina, caviglie appoggiate ai cuscinetti. Estendi le ginocchia fino a quasi completare il ROM, contraendo il quadricipite in cima. Abbassa lentamente. Evita di strappare verso l'alto o di iperestendere il ginocchio.",
            'lying_leg_curl' => 'Sdraiato a pancia in giù sulla macchina, caviglie sotto i cuscinetti. Porta i talloni verso i glutei flettendo i ginocchi, contraendo gli ischiocrurali. Abbassa lentamente. Tieni il bacino a contatto con il cuscinetto.',
            'seated_leg_curl' => "Seduto alla macchina, cosce appoggiate sul cuscinetto anteriore. Porta i talloni verso il basso e indietro flettendo i ginocchi. La posizione seduta allunga l'ischiocrurale anche a livello dell'anca (origine), aumentando l'attivazione rispetto al lying.",
            'barbell_hip_thrust' => "Schiena appoggiata alla panca all'altezza delle scapole, bilanciere sul bacino con cuscinetto. Piedi piatti a terra. Spingi il bacino verso l'alto estendendo l'anca completamente. Gluteo massimamente contratto in cima. Abbassa controllato.",
            'good_morning' => "Bilanciere sul dorso come nello squat. Fai cerniera sull'anca abbassando il busto mantenendo la schiena neutra e le ginocchia leggermente flesse. Scendi fino a quasi parallelo al suolo, poi torna su spingendo i fianchi in avanti.",
            'glute_abduction_machine' => "Seduto alla macchina con cosce all'interno dei cuscinetti. Apri le gambe verso l'esterno contro la resistenza, poi riporta lentamente al centro. Isola il gluteo medio. Il busto può essere leggermente inclinato in avanti per aumentare l'attivazione.",
            'smith_squat' => 'Come lo squat con bilanciere ma con la guida dello Smith Machine. La barra segue una traiettoria fissa, quindi è importante posizionare correttamente i piedi in anticipo. Adatto ai principianti o per isolare meglio il quadricipite con piedi avanzati.',
            'pendulum_squat' => 'Macchina a piastre con baricentro oscillante (pendolo). Schiena appoggiata, piedi sulla pedana. Permette una profondità di squat eccellente con busto verticale e forte enfasi sul quadricipite. Range di movimento ampio con basso stress lombare.',
            'sissy_squat' => 'In piedi (con supporto), inclina il busto indietro e fletti solo le ginocchia portandole in avanti mentre sali in punta di piedi. Isola il quadricipite in modo estremo. Richiede buona mobilità e forza del core. Progressione verso versioni con carico.',
            'walking_lunge' => 'Come gli affondi statici ma invece di tornare indietro si avanza alternando le gambe in sequenza camminando. Ottimo per coordinazione e lavoro metabolico. Bilanciere sul dorso o manubri ai fianchi.',
            'hyperextension_45' => 'Busto sulla panca hyperextension a 45°, piedi bloccati. Parti con il busto quasi verticale, abbassa fino ad avere la schiena parallela o leggermente sotto, poi risali contraendo glutei e ischiocrurali. Mantieni la schiena neutra (non iperestendere in cima).',
            'adductor_machine' => "Seduto alla macchina con le gambe aperte sui cuscinetti laterali. Chiudi le gambe verso il centro contro la resistenza, poi riapri lentamente. Isola gli adduttori. Regola la larghezza di partenza in base alla mobilità dell'anca.",
            'standing_calf_raise' => 'In piedi sulla pedana della macchina, spalle sotto i cuscinetti. Scendi il tallone più in basso possibile (dorsiflexion) poi spingi sulle punte il più in alto possibile (plantarflexion). Pausa di un secondo in cima per la contrazione. Enfatizza il gastrocnemio.',
            'seated_calf_raise' => 'Seduto alla macchina con ginocchia a 90° e cuscinetti sopra le cosce. Stessa esecuzione: scendi il tallone e poi spingi sulle punte. La posizione seduta flette il ginocchio, mettendo il gastrocnemio in posizione più corta e quindi enfatizzando il soleo.',
            'donkey_calf_raise' => 'Busto inclinato in avanti (circa 90°) appoggiato al supporto, piedi sulla pedana. Esegui la plantarflessione come per il calf raise in piedi. La posizione del busto inclina il gastrocnemio verso una tensione diversa rispetto alla variante diritta.',
            'dumbbell_shrug' => 'In piedi, manubri ai fianchi con braccia tese. Alza le spalle verso le orecchie il più possibile (scrollata), poi abbassa lentamente. Non ruotare le spalle né piegare i gomiti. La fase eccentrica lenta massimizza lo stimolo sul trapezio superiore.',
            'cable_face_pull' => "Cavo all'altezza degli occhi con corda. Tira verso il viso aprendo le mani verso l'esterno all'altezza della testa. I gomiti devono salire all'altezza delle spalle o più in alto. Ottimo per il deltoide posteriore, salute della cuffia dei rotatori e postura.",
            'floor_crunch' => 'Sdraiato, ginocchia flesse, mani dietro la testa o sul petto. Solleva solo le scapole dal suolo contraendo il retto addominale, non tirare il collo con le mani. Abbassa lentamente senza posare completamente la testa.',
            'cable_kneeling_crunch' => 'In ginocchio di fronte al cavo alto con corda. Fletti il busto verso il basso come per un crunch, portando i gomiti verso le cosce. Non tirare con le braccia: il movimento è della schiena/addome. Torna su lentamente.',
            'front_plank' => 'Appoggio su avambracci e punte dei piedi, corpo in linea retta. Contrai addome, glutei e quadricipiti per mantenere la posizione. Non lasciare che il bacino cada o si alzi. Respira normalmente. Mantieni la posizione per il tempo prescritto.',
            'russian_twist' => "Seduto con busto inclinato a circa 45°, ginocchia flesse e piedi sollevati (o a terra per variante più facile). Ruota il busto da un lato all'altro toccando il suolo (o portando il peso) ad ogni rotazione. Mantieni il core contratto.",
            'hanging_leg_raise' => "Appeso alla sbarra con presa prona. Porta le gambe tese verso l'alto fino a parallelismo o oltre senza usare l'inerzia. Abbassa lentamente. Per principianti: gambe piegate. Il controllo discendente è fondamentale per attivare il retto addominale.",
            'ab_wheel_rollout' => 'In ginocchio con la ruota a terra, braccia tese. Fai scorrere la ruota in avanti abbassando il busto verso il suolo mantenendo la schiena neutra. Torna su contraendo il core e il dorsale. Non iperestendere la lombare nella fase di allungamento.',
            'cable_woodchopper' => 'Cavo in alto su un lato. Tira la maniglia diagonalmente verso il basso e il lato opposto ruotando il busto. Movimento dal fianco alto al fianco basso. Le braccia restano quasi tese. Isola gli obliqui. Un set per lato.',
            'reverse_crunch' => "Sdraiato, gambe a 90°. Porta il bacino verso il petto sollevando i glutei dal suolo tramite la contrazione del basso addome. Non usare l'inerzia delle gambe. Abbassa lentamente. Variante dei crunch che enfatizza la porzione inferiore del retto.",
        ];

        foreach ($descriptions as $slug => $text) {
            DB::table('exercises')
                ->where('slug', $slug)
                ->whereNull('deleted_at')
                ->update(['execution_description' => $text]);
        }
    }
}
